package com.smates.dbc2.webservicedemo.queryavailable;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-03T19:53:48.225+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "QueryAvailableService")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryAvailableService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAvailable", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.queryavailable.QueryAvailable")
    @WebMethod
    @ResponseWrapper(localName = "queryAvailableResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.queryavailable.QueryAvailableResponse")
    public java.util.List<java.lang.String> queryAvailable();
}
