package com.smates.dbc2.webservicedemo.outputdata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-03T19:47:22.562+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "OutputDataServiceImplService", 
                  wsdlLocation = "http://210.77.67.251:19001/Webservice-Demo/OutputDataServiceWS?wsdl",
                  targetNamespace = "http://impl.service.hhs.com/") 
public class OutputDataServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.hhs.com/", "OutputDataServiceImplService");
    public final static QName OutputDataServiceImplPort = new QName("http://impl.service.hhs.com/", "OutputDataServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://210.77.67.251:19001/Webservice-Demo/OutputDataServiceWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OutputDataServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://210.77.67.251:19001/Webservice-Demo/OutputDataServiceWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OutputDataServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OutputDataServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutputDataServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OutputDataServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OutputDataServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OutputDataServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OutputDataService
     */
    @WebEndpoint(name = "OutputDataServiceImplPort")
    public OutputDataService getOutputDataServiceImplPort() {
        return super.getPort(OutputDataServiceImplPort, OutputDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutputDataService
     */
    @WebEndpoint(name = "OutputDataServiceImplPort")
    public OutputDataService getOutputDataServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OutputDataServiceImplPort, OutputDataService.class, features);
    }

}
