package com.smates.dbc2.webservicedemo.outputdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-03T19:47:22.530+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "OutputDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface OutputDataService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "outputData", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.outputdata.OutputData")
    @WebMethod
    @ResponseWrapper(localName = "outputDataResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.outputdata.OutputDataResponse")
    public java.util.List<com.smates.dbc2.webservicedemo.outputdata.DoubleArray> outputData(
        @WebParam(name = "watershedCode", targetNamespace = "")
        long watershedCode,
        @WebParam(name = "time", targetNamespace = "")
        long time
    );
}
