package com.smates.dbc2.webservicedemo.querystate;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-03T19:52:29.154+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "QueryStateService")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryStateService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryState", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.querystate.QueryState")
    @WebMethod
    @ResponseWrapper(localName = "queryStateResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.querystate.QueryStateResponse")
    public java.lang.String queryState();
}
