package com.smates.dbc2.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-06T20:55:26.434+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "RisDSSModelService")
@XmlSeeAlso({ObjectFactory.class})
public interface RisDSSModelService {

    @WebMethod
    @RequestWrapper(localName = "queryAvailable", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.QueryAvailable")
    @ResponseWrapper(localName = "queryAvailableResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.QueryAvailableResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> queryAvailable();

    @WebMethod
    @RequestWrapper(localName = "start", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.StartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String start(
        @WebParam(name = "watershedCode", targetNamespace = "")
        java.lang.String watershedCode,
        @WebParam(name = "countyCodes", targetNamespace = "")
        java.util.List<java.lang.String> countyCodes,
        @WebParam(name = "countyNames", targetNamespace = "")
        java.util.List<java.lang.String> countyNames,
        @WebParam(name = "timeStart", targetNamespace = "")
        java.lang.String timeStart,
        @WebParam(name = "timeEnd", targetNamespace = "")
        java.lang.String timeEnd,
        @WebParam(name = "timeStep", targetNamespace = "")
        int timeStep,
        @WebParam(name = "prec", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> prec,
        @WebParam(name = "precR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> precR,
        @WebParam(name = "tempAvg", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> tempAvg,
        @WebParam(name = "tempMax", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> tempMax,
        @WebParam(name = "tempMin", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> tempMin,
        @WebParam(name = "outputInd", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> outputInd,
        @WebParam(name = "outputAgr", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> outputAgr,
        @WebParam(name = "outputSer", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> outputSer,
        @WebParam(name = "outputTour", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> outputTour,
        @WebParam(name = "outputTourR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> outputTourR,
        @WebParam(name = "techProgRR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> techProgRR,
        @WebParam(name = "areaAgri", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaAgri,
        @WebParam(name = "areaAgriR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaAgriR,
        @WebParam(name = "areaCropWheat", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropWheat,
        @WebParam(name = "areaCropCorn", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropCorn,
        @WebParam(name = "areaCropOilseed", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropOilseed,
        @WebParam(name = "areaCropOrchard", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropOrchard,
        @WebParam(name = "areaCropCotton", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropCotton,
        @WebParam(name = "areaCropGreenstuff", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropGreenstuff,
        @WebParam(name = "areaCropWheatR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropWheatR,
        @WebParam(name = "areaCropCornR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropCornR,
        @WebParam(name = "areaCropOilseedR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropOilseedR,
        @WebParam(name = "areaCropOrchardR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropOrchardR,
        @WebParam(name = "areaCropCottonR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropCottonR,
        @WebParam(name = "areaCropGreenstuffR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaCropGreenstuffR,
        @WebParam(name = "areaForest", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaForest,
        @WebParam(name = "areaGrass", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaGrass,
        @WebParam(name = "areaWater", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaWater,
        @WebParam(name = "gdp", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> gdp,
        @WebParam(name = "gdpPer", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> gdpPer,
        @WebParam(name = "gdpR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> gdpR,
        @WebParam(name = "gdpPerR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> gdpPerR,
        @WebParam(name = "channelMain", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelMain,
        @WebParam(name = "channelBran", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelBran,
        @WebParam(name = "channelDou", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelDou,
        @WebParam(name = "channelNong", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelNong,
        @WebParam(name = "channelMao", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelMao,
        @WebParam(name = "channelMainWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelMainWUE,
        @WebParam(name = "channelBranWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelBranWUE,
        @WebParam(name = "channelDouWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelDouWUE,
        @WebParam(name = "channelNongWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelNongWUE,
        @WebParam(name = "channelMaoWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> channelMaoWUE,
        @WebParam(name = "areaDripIrri", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> areaDripIrri,
        @WebParam(name = "allowanceInd", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> allowanceInd,
        @WebParam(name = "allowanceAgr", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> allowanceAgr,
        @WebParam(name = "allowanceSer", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> allowanceSer,
        @WebParam(name = "waterAlloMid", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> waterAlloMid,
        @WebParam(name = "waterAlloDown", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> waterAlloDown,
        @WebParam(name = "waterRight", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> waterRight,
        @WebParam(name = "waterSavingTechR", targetNamespace = "")
        java.util.List<com.smates.dbc2.ws.DoubleArray> waterSavingTechR
    );

    @WebMethod
    @RequestWrapper(localName = "queryState", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.QueryState")
    @ResponseWrapper(localName = "queryStateResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.QueryStateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int queryState();

    @WebMethod
    @RequestWrapper(localName = "getDataYearly", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.GetDataYearly")
    @ResponseWrapper(localName = "getDataYearlyResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.ws.GetDataYearlyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.smates.dbc2.ws.DoubleArray> getDataYearly(
        @WebParam(name = "watershedCode", targetNamespace = "")
        long watershedCode,
        @WebParam(name = "year", targetNamespace = "")
        long year
    );
}
