package com.smates.dbc2.webservicedemo.inputdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-03T19:45:27.198+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "InputDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface InputDataService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "inputData", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.inputdata.InputData")
    @WebMethod
    @ResponseWrapper(localName = "inputDataResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.inputdata.InputDataResponse")
    public java.lang.String inputData(
        @WebParam(name = "watershedCode", targetNamespace = "")
        long watershedCode,
        @WebParam(name = "countyCodes", targetNamespace = "")
        java.util.List<java.lang.Long> countyCodes,
        @WebParam(name = "countyNames", targetNamespace = "")
        java.util.List<java.lang.String> countyNames,
        @WebParam(name = "timeStart", targetNamespace = "")
        java.lang.String timeStart,
        @WebParam(name = "timeEnd", targetNamespace = "")
        java.lang.String timeEnd,
        @WebParam(name = "timeStep", targetNamespace = "")
        int timeStep,
        @WebParam(name = "prec", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> prec,
        @WebParam(name = "precR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> precR,
        @WebParam(name = "tempAvg", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempAvg,
        @WebParam(name = "tempMax", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempMax,
        @WebParam(name = "tempMin", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempMin,
        @WebParam(name = "tempAvgR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempAvgR,
        @WebParam(name = "tempMaxR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempMaxR,
        @WebParam(name = "tempMinR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> tempMinR,
        @WebParam(name = "pop", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> pop,
        @WebParam(name = "popR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> popR,
        @WebParam(name = "popAgriR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> popAgriR,
        @WebParam(name = "popAgriRR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> popAgriRR,
        @WebParam(name = "popNonAgriR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> popNonAgriR,
        @WebParam(name = "popNonAgriRR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> popNonAgriRR,
        @WebParam(name = "outputInd", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> outputInd,
        @WebParam(name = "outputAgr", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> outputAgr,
        @WebParam(name = "outputSer", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> outputSer,
        @WebParam(name = "outputTour", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> outputTour,
        @WebParam(name = "outputTourR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> outputTourR,
        @WebParam(name = "techProgRR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> techProgRR,
        @WebParam(name = "areaAgri", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaAgri,
        @WebParam(name = "areaAgriR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaAgriR,
        @WebParam(name = "areaCropWheat", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropWheat,
        @WebParam(name = "areaCropCorn", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropCorn,
        @WebParam(name = "areaCropOilseed", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropOilseed,
        @WebParam(name = "areaCropOrchard", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropOrchard,
        @WebParam(name = "areaCropCotton", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropCotton,
        @WebParam(name = "areaCropGreenstuff", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropGreenstuff,
        @WebParam(name = "areaCropWheatR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropWheatR,
        @WebParam(name = "areaCropCornR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropCornR,
        @WebParam(name = "areaCropOilseedR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropOilseedR,
        @WebParam(name = "areaCropOrchardR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropOrchardR,
        @WebParam(name = "areaCropCottonR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropCottonR,
        @WebParam(name = "areaCropGreenstuffR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaCropGreenstuffR,
        @WebParam(name = "areaWetland", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaWetland,
        @WebParam(name = "areaForest", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaForest,
        @WebParam(name = "areaGrass", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaGrass,
        @WebParam(name = "areaWater", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaWater,
        @WebParam(name = "areaWetlandR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaWetlandR,
        @WebParam(name = "areaForestR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaForestR,
        @WebParam(name = "areaGrassR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaGrassR,
        @WebParam(name = "areaWaterR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaWaterR,
        @WebParam(name = "gdp", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> gdp,
        @WebParam(name = "gdpPer", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> gdpPer,
        @WebParam(name = "gdpR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> gdpR,
        @WebParam(name = "gdpPerR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> gdpPerR,
        @WebParam(name = "policyPop", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> policyPop,
        @WebParam(name = "channelMain", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMain,
        @WebParam(name = "channelBran", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelBran,
        @WebParam(name = "channelDou", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelDou,
        @WebParam(name = "channelNong", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelNong,
        @WebParam(name = "channelMao", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMao,
        @WebParam(name = "channelMainWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMainWUE,
        @WebParam(name = "channelBranWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelBranWUE,
        @WebParam(name = "channelDouWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelDouWUE,
        @WebParam(name = "channelNongWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelNongWUE,
        @WebParam(name = "channelMaoWUE", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMaoWUE,
        @WebParam(name = "channelMainWUER", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMainWUER,
        @WebParam(name = "channelBranWUER", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelBranWUER,
        @WebParam(name = "channelDouWUER", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelDouWUER,
        @WebParam(name = "channelNongWUER", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelNongWUER,
        @WebParam(name = "channelMaoWUER", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> channelMaoWUER,
        @WebParam(name = "areaDripIrri", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> areaDripIrri,
        @WebParam(name = "allowanceInd", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> allowanceInd,
        @WebParam(name = "allowanceAgr", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> allowanceAgr,
        @WebParam(name = "allowanceSer", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> allowanceSer,
        @WebParam(name = "waterAlloMid", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> waterAlloMid,
        @WebParam(name = "waterAlloDown", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> waterAlloDown,
        @WebParam(name = "waterRight", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> waterRight,
        @WebParam(name = "waterSavingTechR", targetNamespace = "")
        java.util.List<com.smates.dbc2.webservicedemo.inputdata.DoubleArray> waterSavingTechR
    );
}
