package com.smates.dbc2.webservicedemo.inputdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-26T12:51:11.163+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.hhs.com/", name = "InputDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface InputDataService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "inputData", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.inputdata.InputData")
    @WebMethod
    @ResponseWrapper(localName = "inputDataResponse", targetNamespace = "http://service.hhs.com/", className = "com.smates.dbc2.webservicedemo.inputdata.InputDataResponse")
    public java.lang.String inputData(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
